"""Generate PVE hookscript snippets for pve-lxc containers."""

import logging
from pathlib import Path

from kento.errors import StateError

logger = logging.getLogger("kento")


def generate_lxc_snippets_wrapper(hook_path: Path) -> str:
    """Thin wrapper that maps PVE hookscript phases to kento-hook types."""
    return f"""#!/bin/sh
# Generated by kento. PVE strips lxc.hook.start-host, so we route
# post-start / post-stop through this snippets wrapper to fire the
# per-container kento-hook (the plain-LXC hook.sh).
VMID="$1"
PHASE="$2"
case "$PHASE" in
    post-start)
        exec "{hook_path}" "$VMID" "" "start-host"
        ;;
    post-stop)
        exec "{hook_path}" "$VMID" "" "post-stop"
        ;;
esac
exit 0
"""


def write_lxc_snippets_wrapper(vmid: int, hook_path: Path, *,
                                snippets_dir: Path | None = None,
                                storage_name: str | None = None) -> str:
    """Write the wrapper and return a PVE storage ref."""
    if snippets_dir is None or storage_name is None:
        from kento.vm_hook import find_snippets_dir
        snippets_dir, storage_name = find_snippets_dir()
    wrapper_name = f"kento-lxc-{vmid}.sh"
    wrapper_path = snippets_dir / wrapper_name
    wrapper_path.write_text(generate_lxc_snippets_wrapper(hook_path))
    wrapper_path.chmod(0o755)
    return f"{storage_name}:snippets/{wrapper_name}"


def delete_lxc_snippets_wrapper(vmid: int) -> None:
    """Delete the wrapper (no-op if missing)."""
    try:
        from kento.vm_hook import find_snippets_dir
        snippets_dir, _ = find_snippets_dir()
        wrapper = snippets_dir / f"kento-lxc-{vmid}.sh"
        wrapper.unlink(missing_ok=True)
    except StateError:
        # find_snippets_dir() couldn't locate the snippets storage (no longer
        # enabled / unlocatable). We can't compute the wrapper path, so the
        # file (if any) is left behind. Warn rather than silently reporting a
        # clean destroy so a leaked wrapper can be cleaned up manually.
        logger.warning(
            "could not locate snippets storage to remove the "
            "kento-lxc-%s.sh hookscript wrapper; it may need manual cleanup",
            vmid,
        )
